#!/usr/bin/env python3
"""Generate Phase 2 research JSON files."""
import json
from pathlib import Path

OUT = Path(__file__).resolve().parents[1] / "results"

ITEMS = [
    {
        "file": "Problem_and_opportunity.json",
        "data": {
            "name": "Problem and opportunity",
            "category": "Landscape",
            "official_url": None,
            "already_exists": "partial_fragment",
            "existence_evidence": "Per-user/session KV and provider prefix caching are production features (Anthropic prompt caching, vLLM/LMCache). Org-wide semantic and retrieval caches exist as gateway features (Portkey, LiteLLM) and libraries (GPTCache) but not as a unified compliance-aware cross-user product. Enterprises report 40-80% potential cost reduction from semantic caching in repetitive workloads (industry blogs and Percona benchmarks).",
            "gap_vs_vision": "The vision is thousands of employees across chatbots, coding tools, and doc search reusing safe work across users. Today most caching is per-session, per-app, or ungoverned shared Redis. Missing: central policy lanes, clearance-tier keys, coordinated invalidation on doc version, and audit proving User B never received User A's PII.",
            "summary": "Large organizations pay repeatedly for the same LLM work: similar questions, same handbook chunks, identical system prompts. Single-user KV cache only helps the same person on the next turn with an identical prefix. Cross-user reuse requires deliberate cache classes and governance, not flipping one semantic-cache switch.",
            "how_it_works": "Workload pattern: high duplicate intent, low duplicate bytes. Employees paraphrase FAQs, policy, and engineering docs. Without org cache: every user triggers full embed-retrieve-generate. With org cache: shared tiers (retrieval, exact FAQ, guarded semantic) keyed by corpus version and sensitivity tier.",
            "integration_points": "Sits above all AI surfaces: API gateway (LiteLLM/Portkey), RAG services (Qdrant), identity/clearance from IAM, DLP on ingress, async write-back workers, observability for hit rate and leakage incidents.",
            "correctness_risks": "Treating org cache as one global bucket causes wrong answers and regulatory breach. Under-caching leaves money and carbon on the table.",
            "cost_latency_impact": "Industry reports: semantic hits can be 250x faster than full LLM calls; 40-80% cost reduction possible on repetitive traffic at 60% hit rates (vendor/anecdotal—varies by workload). Cross-user retrieval cache often yields large savings with lower risk than answer cache.",
            "environmental_impact": "Fewer tokens and GPU cycles reduce operational carbon; shared caching amplifies savings vs per-user-only reuse.",
            "cross_user_sharing": "org_wide_with_guards — only via tiered lanes; never one undifferentiated pool",
            "pii_and_compliance_controls": "Mandatory: partition by org_id + sensitivity + corpus_version; scrub before hash/embed; block high-PII prompts from shared lanes; audit hits without logging raw PII.",
            "org_scale_patterns": "Single logical cache plane, many physical namespaces (faq, team-project, user-private). All tools route through gateway or shared SDK enforcing same key schema.",
            "rollout_priority": "Foundation: define lanes and metrics before enabling cross-user writes",
            "makes_sense_verdict": "strong_yes",
            "makes_sense_rationale": "Problem is real, measurable, and aligned with cost/ESG goals. Exists as fragments; integrator opportunity is compliance-safe cross-user reuse.",
            "primary_sources": [
                {"title": "Anthropic prompt caching overview", "url": "https://github.com/anthropics/skills/blob/main/skills/claude-api/shared/prompt-caching.md"},
                {"title": "Percona semantic caching benchmarks", "url": "https://www.percona.com/blog/semantic-caching-for-llm-apps-reduce-costs-by-40-80-and-speed-up-by-250x/"},
                {"title": "LMCache enterprise KV layer", "url": "https://arxiv.org/pdf/2510.09665"},
            ],
            "uncertain": [],
        },
    },
    {
        "file": "Cross-user_shared_cache_safety_model.json",
        "data": {
            "name": "Cross-user shared cache safety model",
            "category": "Governance",
            "official_url": None,
            "already_exists": "partial_fragment",
            "existence_evidence": "Gateways offer org-level caching (Portkey) but rarely ship complete ABAC+DLP+lane models. Cloud providers offer encryption and tenant IDs; enterprises implement classification via internal policy engines. vCache and similar research address correctness bounds, not HR/legal tenancy.",
            "gap_vs_vision": "No standard SKU for 'safe cross-user LLM cache.' Organizations must define lanes: user-private, team+clearance, org-static FAQ. Vision adds write/read policy, erasure, and prohibited content classes per lane.",
            "summary": "Framework for when User B may receive cached artifacts derived from User A's traffic. Separates cacheable public intent from personal context (HR, health, proprietary code, named individuals).",
            "how_it_works": "Lanes: (1) user-private—no cross-user reads; (2) team/project—shared if same clearance+corpus; (3) org-static—scrubbed FAQs and retrieval-only keys. Keys include org_id, lane, sensitivity, corpus_version, model_id. Write path: classify prompt, scrub, reject or route. Read path: match lane+clearance+version. Optional LLM judge on grey-zone semantic hits.",
            "integration_points": "Gateway middleware, RAG preprocessor, SIEM/audit bus, IAM attributes, DLP/NER services, legal retention policies.",
            "correctness_risks": "Semantic false positive across users is a data breach and wrong decision. Coding tools leaking snippets across repos. Stale policy docs after version bump.",
            "cost_latency_impact": "Governance adds milliseconds (classification) vs dollars saved on hits; net positive when hit rate >5-10% on shared lanes.",
            "environmental_impact": "Indirect: safer sharing enables broader reuse and fewer redundant GPU jobs.",
            "cross_user_sharing": "org_wide_with_guards — lane-dependent",
            "pii_and_compliance_controls": "Normalize+hash only after redaction; never key on raw employee identifiers; encrypt at rest; TTL and legal hold; right-to-erasure deletes by key prefix; log cache_key_hash not plaintext.",
            "org_scale_patterns": "Central policy service consumed by all AI tools; forbidden to bypass with per-team Redis without taxonomy.",
            "rollout_priority": "Week 0–1: design lanes before any cross-user cache writes",
            "makes_sense_verdict": "strong_yes",
            "makes_sense_rationale": "Without this model, cross-user caching is unacceptable for regulated enterprises; with it, Tier 3 and gated Tier 1 become deployable.",
            "primary_sources": [
                {"title": "vCache verified semantic cache", "url": "https://arxiv.org/abs/2502.03771"},
                {"title": "Portkey semantic threshold guidance", "url": "https://portkey.ai/blog/semantic-caching-thresholds/"},
            ],
            "uncertain": ["official_url"],
        },
    },
    {
        "file": "Multi-tier_reference_architecture.json",
        "data": {
            "name": "Multi-tier reference architecture",
            "category": "Architecture",
            "official_url": None,
            "already_exists": "partial_fragment",
            "existence_evidence": "Each tier has independent products (Redis, Qdrant, GPTCache, LMCache, provider APIs). Introl and ZeroEntropy document multi-tier prefix+semantic patterns in 2025. No single vendor bundles all five tiers with unified invalidation.",
            "gap_vs_vision": "Unified write-back to all tiers async, single doc_corpus_version invalidating T1-T3 together, and cross-tool gateway enforcement.",
            "summary": "Composable pipeline: Tier 0 normalize → T1 exact → T2 semantic answer → T3 retrieval → T4 prefix KV → LLM; async populate allowed tiers on miss.",
            "how_it_works": "Request flows cheapest-first. Misses fall through. Response worker writes to tiers permitted by classification. Invalidation: model change busts all; corpus_version busts T1-T3; prefix break busts T4 only.",
            "integration_points": "Ingress gateway, RAG service, vector DB, Redis, inference engine, message queue for write-back and audit.",
            "correctness_risks": "Tier ordering wrong (semantic before retrieval) wastes money. Writing personal answers to org lane.",
            "cost_latency_impact": "Stacking tiers compounds hit probability; T3+T4 often dominate RAG savings with lower risk than T2 alone.",
            "environmental_impact": "Multi-tier maximizes compute avoidance per request.",
            "cross_user_sharing": "org_wide_with_guards — per-tier policy",
            "pii_and_compliance_controls": "Per-tier write matrix: T3 org-wide ok with version keys; T2 requires scrub+lane; T4 only if prefix has no user-specific bytes.",
            "org_scale_patterns": "One architecture diagram, many deployables; shared observability dashboard for hit rate by tier and lane.",
            "rollout_priority": "Design all tiers; ship T3+T4 first, then T1, then T2",
            "makes_sense_verdict": "strong_yes",
            "makes_sense_rationale": "Matches industry direction and user clarification; integration is the product.",
            "primary_sources": [
                {"title": "Prompt caching infrastructure guide", "url": "https://introl.com/blog/prompt-caching-infrastructure-llm-cost-latency-reduction-guide-2025"},
                {"title": "ZeroEntropy prompt caching concepts", "url": "https://zeroentropy.dev/concepts/prompt-caching/"},
            ],
            "uncertain": ["official_url"],
        },
    },
    {
        "file": "Tier_0_query_normalization.json",
        "data": {
            "name": "Tier 0 query normalization",
            "category": "Architecture",
            "official_url": None,
            "already_exists": "partial_fragment",
            "existence_evidence": "Exact caches implicitly normalize in some gateways; GPTCache and blogs recommend normalization for hit rate. DLP/NER scrubbing is enterprise-standard but not part of cache libraries by default.",
            "gap_vs_vision": "Coupled normalize+classify+route-to-lane as mandatory pre-cache step for cross-user keys.",
            "summary": "Pre-cache hygiene: lowercase, whitespace, punctuation rules, optional stemming; SHA-256 for Tier 1; embedding for Tier 2/3 after scrub.",
            "how_it_works": "Pipeline: raw query → locale rules → PII detect/redact → optional attachment strip → hash string + embed vector. Order: hash check before embed to save embedding cost on exact hits.",
            "integration_points": "First hop in gateway or RAG API; shared library for all internal AI tools.",
            "correctness_risks": "Over-aggressive normalization merges distinct intents; under-normalization splits hits. Redaction alters meaning for legal queries.",
            "cost_latency_impact": "Hash nearly free; embedding costs tokens/API—defer until T1 miss. Scrub adds 10-50ms depending on DLP.",
            "environmental_impact": "Minimal direct impact; enables higher hit rates.",
            "cross_user_sharing": "org_wide_with_guards — output of Tier 0 feeds only approved lanes",
            "pii_and_compliance_controls": "Block or downgrade to user-private lane when PII detectors fire; never org-cache raw prompts with emails/SSN/names.",
            "org_scale_patterns": "Single normalization spec versioned (norm_v3) included in cache keys.",
            "rollout_priority": "Week 1 — prerequisite for safe T1 and cross-user keys",
            "makes_sense_verdict": "strong_yes",
            "makes_sense_rationale": "Cheap, mandatory for cross-user exact cache and compliance.",
            "primary_sources": [
                {"title": "GPTCache semantic cache design", "url": "https://github.com/zilliztech/gptcache"},
            ],
            "uncertain": ["official_url", "environmental_impact"],
        },
    },
    {
        "file": "Tier_1_exact_hash_cache.json",
        "data": {
            "name": "Tier 1 exact hash cache",
            "category": "Architecture",
            "official_url": "https://redis.io/docs/latest/develop/ai/redisvl/user_guide/langcache_semantic_cache/",
            "already_exists": "full_product",
            "existence_evidence": "Redis, Portkey simple cache, LiteLLM redis cache, LangChain RedisCache—all production. Sub-millisecond GET latency typical.",
            "gap_vs_vision": "Org namespaces with clearance and corpus_version in key; central FAQ allowlist; no raw-user-keyed entries in org pool.",
            "summary": "Key = hash(normalized_query + lane + corpus_version + model_id); value = response metadata and text; TTL or version-based expiry.",
            "how_it_works": "SHA-256 or similar on normalized string. Redis GET; on miss continue pipeline. Invalidate on corpus_version or model bump. Hit counter for analytics.",
            "integration_points": "Redis/Valkey cluster shared by gateway; optional per-region replicas.",
            "correctness_risks": "Low for exact match if normalization stable. Stale FAQ if version tag omitted.",
            "cost_latency_impact": "~100µs–2ms latency; saves full LLM cost on hit. Hit rates highest on IT/HR FAQs (10-40% of traffic in repetitive orgs—estimate, workload-dependent).",
            "environmental_impact": "High savings per hit—no GPU for cached answer.",
            "cross_user_sharing": "org_wide_static_only — for scrubbed FAQ lane; else same_tenant_only",
            "pii_and_compliance_controls": "Only cache if post-Tier-0 classification allows org:faq lane; key must not include user id.",
            "org_scale_patterns": "Redis cluster with key prefix org:{id}:lane:faq:v{corpus}:sha256(...)",
            "rollout_priority": "Month 2 — after log analysis identifies top exact repeats",
            "makes_sense_verdict": "yes_with_caveats",
            "makes_sense_rationale": "Easy win for FAQ traffic cross-user; limited value for paraphrased enterprise questions without Tier 2/3.",
            "primary_sources": [
                {"title": "Portkey simple cache docs", "url": "https://docs.portkey.ai/docs/product/ai-gateway/cache-simple-and-semantic"},
                {"title": "LangChain Redis cache", "url": "https://docs.langchain.com/oss/python/integrations/caches/redis_llm_caching"},
            ],
            "uncertain": [],
        },
    },
    {
        "file": "Tier_2_semantic_response_cache.json",
        "data": {
            "name": "Tier 2 semantic response cache",
            "category": "Architecture",
            "official_url": "https://arxiv.org/abs/2502.03771",
            "already_exists": "partial_fragment",
            "existence_evidence": "GPTCache, Portkey semantic (enterprise), LiteLLM redis-semantic/qdrant-semantic, Redis LangCache. vCache adds per-entry thresholds and error bounds (research/productionizing). Portkey cites ~0.95 similarity and 99% accuracy targets on large traffic.",
            "gap_vs_vision": "Cross-user answer store with lane policy, vCache-style guarantees, and prohibition on open-ended HR/legal/coding lanes org-wide.",
            "summary": "Store query embedding + full model response; ANN lookup; return if similarity > threshold (often 0.95-0.97 for enterprise).",
            "how_it_works": "On miss: generate answer, async embed query, upsert vector DB with metadata (lane, corpus_version, model). On hit: return cached response if similarity and policy checks pass. Staleness: reject if doc_corpus_version mismatch.",
            "integration_points": "Qdrant/Milvus/Pinecone/Redis vector; embedding API; gateway or GPTCache in app.",
            "correctness_risks": "False positives—wrong answer confidently. Static global thresholds suboptimal (vCache paper). Cross-user leakage if personal context embedded in cached query.",
            "cost_latency_impact": "Embedding cost on miss (~23ms cited in benchmarks) vs seconds for LLM. Hit saves output tokens and latency. Threshold too low increases errors; too low hit rate.",
            "environmental_impact": "Strong operational savings when hits are safe and frequent.",
            "cross_user_sharing": "org_wide_with_guards — FAQ lane only by default; user-private otherwise",
            "pii_and_compliance_controls": "Never org-cache raw prompts; scrub before embed; optional secondary verifier on hits; separate indexes per sensitivity tier.",
            "org_scale_patterns": "Gateway-enforced semantic mode per route; coding chat routes disable org-wide semantic.",
            "rollout_priority": "Month 3+ — after T3/T4/T1 and safety model proven",
            "makes_sense_verdict": "yes_with_caveats",
            "makes_sense_rationale": "High ROI on repetitive low-risk queries; unacceptable as default org-wide without governance.",
            "primary_sources": [
                {"title": "vCache paper", "url": "https://arxiv.org/abs/2502.03771"},
                {"title": "GPTCache", "url": "https://github.com/zilliztech/gptcache"},
                {"title": "Portkey semantic caching", "url": "https://docs.portkey.ai/docs/product/ai-gateway/cache-simple-and-semantic"},
            ],
            "uncertain": [],
        },
    },
    {
        "file": "Tier_3_RAG_retrieval_cache.json",
        "data": {
            "name": "Tier 3 RAG retrieval cache",
            "category": "Architecture",
            "official_url": None,
            "already_exists": "partial_fragment",
            "existence_evidence": "DIY pattern documented in RAG blogs; not a named feature in most gateways. Research: TurboRAG, CacheBlend, Cache-Craft precompute/reuse chunk KV and retrieval state. LMCache ecosystem for KV reuse adjacent to retrieval.",
            "gap_vs_vision": "First-class product feature: hash(embed_bytes + filter + top_k + corpus_version + clearance) → chunk_ids with gateway integration and cross-user defaults on.",
            "summary": "Cache the expensive retrieval step—embedding query, vector search, top-K chunk IDs/scores—not necessarily the final natural language answer.",
            "how_it_works": "Key includes query embedding fingerprint (or hash of normalized text used for embed), retrieval filters, k, corpus_version, clearance. Value: chunk_ids, scores, optional chunk text hashes. On hit: skip Qdrant ANN; assemble prompt; still run generation (allows per-user question suffix). Invalidate when corpus_version changes.",
            "integration_points": "RAG service between embed and LLM; Redis for hot keys; ties to document CMS version API.",
            "correctness_risks": "Lower than T2—users get fresh answers from same evidence. Wrong chunks if embed similar but intent differs—mitigate with stricter key or re-rank on hit.",
            "cost_latency_impact": "Eliminates duplicate ANN and chunk fetch for N analysts on same contract section—often large in enterprise RAG. Embedding still needed unless query text hash hits.",
            "environmental_impact": "Reduces embed API calls and vector DB load; generation still runs.",
            "cross_user_sharing": "org_wide_with_guards — best cross-user tier when keyed by corpus+clearance not user",
            "pii_and_compliance_controls": "Do not store user text in key; clearance in key; retrieval filters enforce ABAC; no chunk from restricted docs in shared entry.",
            "org_scale_patterns": "Shared Redis layer in front of Qdrant for all RAG apps; metrics on retrieval hit rate.",
            "rollout_priority": "Week 1–2 — highest priority per architecture review",
            "makes_sense_verdict": "strong_yes",
            "makes_sense_rationale": "Core fit for thousands of users searching same docs; safest major cross-user win.",
            "primary_sources": [
                {"title": "TurboRAG EMNLP 2025", "url": "https://aclanthology.org/anthology-files/anthology-files/pdf/emnlp/2025.emnlp-main.334.pdf"},
                {"title": "Cache-Craft SIGMOD 2025", "url": "https://skejriwal44.github.io/docs/CacheCraft_SIGMOD_2025.pdf"},
            ],
            "uncertain": ["official_url"],
        },
    },
    {
        "file": "Tier_4_provider_prefix_KV_cache.json",
        "data": {
            "name": "Tier 4 provider prefix KV cache",
            "category": "Architecture",
            "official_url": "https://github.com/anthropics/skills/blob/main/skills/claude-api/shared/prompt-caching.md",
            "already_exists": "full_product",
            "existence_evidence": "Anthropic cache_control ephemeral (5m TTL, 1h option); OpenAI and Google analogous features. LMCache for self-hosted cross-request KV. Requires byte-identical prefix; min token thresholds (e.g. 1024 Sonnet).",
            "gap_vs_vision": "Cross-user only when many users share identical assembled prefix (same system + same retrieved bundle). Org must standardize prompt assembly across tools.",
            "summary": "Provider or inference engine reuses KV states for identical leading tokens; user query must be suffix; structure [system][retrieved context][user query].",
            "how_it_works": "Mark cache_control on last block of shared prefix. cache_read_input_tokens billed ~10% of input. Writes cost premium (~125%). Breakpoints (up to 4 on Anthropic) for layered invalidation. Model switch invalidates.",
            "integration_points": "API client libraries; prompt templates in RAG; vLLM+LMCache for on-prem.",
            "correctness_risks": "Single byte change invalidates prefix. Timestamps in system prompt kill hits. User-specific text before shared context prevents cross-user benefit.",
            "cost_latency_impact": "25-35% total cost reduction possible when large prefix reused (production reports); 80-90% on cached input token portion. Latency drops on prefill skip.",
            "environmental_impact": "Major GPU/API energy reduction on cache reads.",
            "cross_user_sharing": "org_wide_static_only — when prefix identical for all users in cohort",
            "pii_and_compliance_controls": "Never put PII in cached prefix; user message after breakpoint; audit cache_read tokens per request.",
            "org_scale_patterns": "Shared prompt templates; retrieved bundle hash in observability; warm cache for popular doc clusters.",
            "rollout_priority": "Week 3–4 — prompt audit and cache_control markers",
            "makes_sense_verdict": "strong_yes",
            "makes_sense_rationale": "Free/low-integration win for API users; complements but does not replace cross-user semantic/retrieval tiers.",
            "primary_sources": [
                {"title": "Anthropic prompt caching skill", "url": "https://github.com/anthropics/skills/blob/main/skills/claude-api/shared/prompt-caching.md"},
                {"title": "LMCache paper", "url": "https://arxiv.org/pdf/2510.09665"},
            ],
            "uncertain": [],
        },
    },
]

# Continue with remaining items in second batch - I'll append via another write or extend file
# For brevity in script, define remaining in same file below

REMAINING = [
    {
        "file": "GPTCache.json",
        "data": {
            "name": "GPTCache",
            "category": "Products and OSS",
            "official_url": "https://github.com/zilliztech/gptcache",
            "already_exists": "full_product",
            "existence_evidence": "Open-source Zilliz project; LangChain/LlamaIndex integrations; pluggable embedders, vector stores (Milvus, FAISS, Redis, Qdrant), SQLite/Postgres response store. Active ecosystem though maintenance varies.",
            "gap_vs_vision": "Library per app—not org gateway with IAM lanes. Teams must implement cross-user policy themselves.",
            "summary": "Python semantic cache framework: embed query, similarity search, return stored LLM response on match.",
            "how_it_works": "Modular: embedding function, vector store, similarity evaluator, cache storage, optional pre/post processors. Configurable threshold and eviction.",
            "integration_points": "Application code or LangChain set_llm_cache; can back with Qdrant matching org stack.",
            "correctness_risks": "DIY thresholds; no built-in corpus versioning or clearance; false positive rate team-owned.",
            "cost_latency_impact": "Documented 2-10x faster on hits vs OpenAI round-trip in project materials; depends on embed model choice.",
            "environmental_impact": "Reduces API calls on hits.",
            "cross_user_sharing": "same_tenant_only — unless app wraps with org key schema",
            "pii_and_compliance_controls": "Not built-in; must wrap writes with scrubbing and lane keys.",
            "org_scale_patterns": "Multiple services each running GPTCache → fragmented; prefer gateway unless RAG-specific Tier 3 logic here.",
            "rollout_priority": "Optional for RAG service Tier 2 prototype",
            "makes_sense_verdict": "yes_with_caveats",
            "makes_sense_rationale": "Good for controlled pilots; not sufficient alone for enterprise-wide compliance story.",
            "primary_sources": [{"title": "GPTCache GitHub", "url": "https://github.com/zilliztech/gptcache"}],
            "uncertain": [],
        },
    },
    {
        "file": "LiteLLM_proxy_caching.json",
        "data": {
            "name": "LiteLLM proxy caching",
            "category": "Products and OSS",
            "official_url": "https://docs.litellm.ai/docs/proxy/caching",
            "already_exists": "full_product",
            "existence_evidence": "Supports in-memory, disk, Redis, S3, GCS; redis-semantic and qdrant-semantic with similarity_threshold; Redis Stack/RediSearch required for semantic (common ops friction). Redis+Qdrant recipe from Redis developer relations.",
            "gap_vs_vision": "No native retrieval-tier or clearance keys; cross-user safe only with config discipline and external policy layer.",
            "summary": "OpenAI-compatible proxy caching all org LLM traffic—exact and semantic at ingress.",
            "how_it_works": "config.yaml litellm_settings.cache=true; cache_params type redis|redis-semantic|qdrant-semantic; optional TTL and namespace.",
            "integration_points": "Central proxy for chatbots, IDE plugins pointing to proxy, cost tracking.",
            "correctness_risks": "Semantic threshold 0.8 default in docs may be too loose for enterprise; shared cache without namespace leaks across envs.",
            "cost_latency_impact": "Org-wide hit rate aggregation possible; one place to measure savings.",
            "environmental_impact": "Centralized reduction of duplicate calls.",
            "cross_user_sharing": "org_wide_with_guards — requires custom key namespace + route rules",
            "pii_and_compliance_controls": "Add gateway hook for scrub/classify before cache; separate Redis DB per sensitivity.",
            "org_scale_patterns": "Single LiteLLM deployment HA pair; Redis cluster backend.",
            "rollout_priority": "Week 2–4 for gateway + Redis exact; semantic after policy",
            "makes_sense_verdict": "strong_yes",
            "makes_sense_rationale": "Best OSS fit for multi-tool org entry point per tool-discovery; pair with custom Tier 3.",
            "primary_sources": [
                {"title": "LiteLLM caching docs", "url": "https://docs.litellm.ai/docs/proxy/caching"},
                {"title": "Redis LiteLLM recipe", "url": "https://redis.io/blog/scale-your-llm-gateway/"},
            ],
            "uncertain": [],
        },
    },
    {
        "file": "Portkey_AI_gateway.json",
        "data": {
            "name": "Portkey AI gateway",
            "category": "Products and OSS",
            "official_url": "https://docs.portkey.ai/docs/product/ai-gateway/cache-simple-and-semantic",
            "already_exists": "full_product",
            "existence_evidence": "Simple cache all plans; semantic enterprise with Milvus/Pinecone; SEMANTIC_CACHE_SIMILARITY_THRESHOLD default 0.95; analytics on hit rate and cost savings; customer claims of $500K+ savings at scale.",
            "gap_vs_vision": "Semantic cache enterprise-only; no retrieval-tier; cross-user compliance is customer-configured not opinionated lanes.",
            "summary": "Managed/self-hosted AI gateway with exact and semantic caching plus observability and guardrails.",
            "how_it_works": "Per-request cache mode simple|semantic; env vars for embed provider and vector DB; internal threshold tuning marketed at 99% accuracy on validated traffic.",
            "integration_points": "Drop-in OpenAI-compatible endpoint; virtual keys; audit logs.",
            "correctness_risks": "Opaque threshold—less control than vCache DIY; vendor lock-in for semantic plane.",
            "cost_latency_impact": "Strong for teams wanting managed ops; semantic needs vector DB cost.",
            "environmental_impact": "Indirect via reduced LLM calls.",
            "cross_user_sharing": "org_wide_with_guards — shared gateway cache pool per deployment",
            "pii_and_compliance_controls": "Guardrails PII filters exist; must configure not to semantic-cache sensitive routes.",
            "org_scale_patterns": "SOC2/HIPAA options; good for regulated buyers preferring vendor ops.",
            "rollout_priority": "Alternative to LiteLLM if budget for enterprise",
            "makes_sense_verdict": "yes_with_caveats",
            "makes_sense_rationale": "Strong buy path if self-hosting Redis Stack is undesirable; still need Tier 3 in RAG.",
            "primary_sources": [
                {"title": "Portkey cache docs", "url": "https://docs.portkey.ai/docs/product/ai-gateway/cache-simple-and-semantic"},
                {"title": "Portkey semantic thresholds blog", "url": "https://portkey.ai/blog/semantic-caching-thresholds/"},
            ],
            "uncertain": [],
        },
    },
    {
        "file": "Redis_LangCache_and_langchain_redis.json",
        "data": {
            "name": "Redis LangCache and langchain-redis",
            "category": "Products and OSS",
            "official_url": "https://redis.io/docs/latest/develop/ai/redisvl/user_guide/langcache_semantic_cache/",
            "already_exists": "full_product",
            "existence_evidence": "langchain-redis: RedisCache, RedisSemanticCache (Redis Stack), LangCacheSemanticCache managed API. Redis positions LangCache as managed semantic cache with server-side embeddings.",
            "gap_vs_vision": "Cache backend not full org policy layer; LangChain-centric vs all coding tools unless proxied.",
            "summary": "Redis-backed exact and semantic LLM caches with optional fully managed LangCache service.",
            "how_it_works": "RedisSemanticCache: client embeds, RediSearch vector index. LangCache: cache_id + api_key, server-side embed, distance_threshold on check.",
            "integration_points": "LangChain apps; can sit behind custom gateway wrapping same Redis keys.",
            "correctness_risks": "Redis Stack module missing breaks semantic (common LiteLLM issue). Managed LangCache less control over embed model.",
            "cost_latency_impact": "Sub-ms vector search cited in industry posts; managed service adds vendor fee.",
            "environmental_impact": "Standard cache benefits.",
            "cross_user_sharing": "org_wide_with_guards — shared Redis with key prefixes",
            "pii_and_compliance_controls": "Use Redis ACLs + key taxonomy; LangCache attributes for pre-configured filters only.",
            "org_scale_patterns": "Enterprise Redis cluster many teams already operate; LangCache if avoid ops.",
            "rollout_priority": "Backend choice for LiteLLM redis-semantic or LangChain services",
            "makes_sense_verdict": "yes_with_caveats",
            "makes_sense_rationale": "Natural store for T1 and T2 if already Redis-heavy; pair with gateway for non-LangChain tools.",
            "primary_sources": [
                {"title": "LangCache user guide", "url": "https://redis.io/docs/latest/develop/ai/redisvl/user_guide/langcache_semantic_cache/"},
                {"title": "langchain-redis", "url": "https://github.com/langchain-ai/langchain-redis"},
            ],
            "uncertain": [],
        },
    },
    {
        "file": "LMCache_and_distributed_KV_reuse.json",
        "data": {
            "name": "LMCache and distributed KV reuse",
            "category": "Products and OSS",
            "official_url": "https://arxiv.org/pdf/2510.09665",
            "already_exists": "full_product",
            "existence_evidence": "LMCache OSS widely adopted for enterprise KV layer; CPU offload, hierarchical storage, PD disaggregation; Momento integration reports >50% TTFT reduction on cold start with distributed cache. Complements vLLM/SGLang.",
            "gap_vs_vision": "Inference-layer KV reuse across requests/nodes—not semantic cross-user answer cache. Helps when prefix identical (including shared RAG context), not paraphrased queries.",
            "summary": "Treats KV cache as first-class reusable object across machines and storage tiers for self-hosted LLMs.",
            "how_it_works": "Store/move KV blocks; prefix matching; integrate with paged attention engines; optional remote storage (S3 tiering with Momento MAX).",
            "integration_points": "vLLM, SGLang, on-prem GPU clusters; not Claude API unless hybrid architecture.",
            "correctness_risks": "Chunk ordering and cross-attention issues similar to CacheBlend research when naively concatenating KVs.",
            "cost_latency_impact": "Significant throughput and TTFT gains in cited deployments; storage and network costs.",
            "environmental_impact": "GreenCache paper: KV storage has embodied carbon; net benefit when hit rate high and CI high.",
            "cross_user_sharing": "org_wide_static_only — when different users share exact same context bytes",
            "pii_and_compliance_controls": "KV blocks may contain attention state derived from private text—treat shared KV as sensitive as source prefix; isolate by tenant on GPU cluster.",
            "org_scale_patterns": "Platform team running internal model serving; pairs with Tier 4 prompt design.",
            "rollout_priority": "If self-hosting LLMs; parallel to API prompt caching",
            "makes_sense_verdict": "yes_with_caveats",
            "makes_sense_rationale": "Essential for on-prem inference scale; orthogonal to semantic org cache for API-only shops.",
            "primary_sources": [
                {"title": "LMCache arXiv", "url": "https://arxiv.org/pdf/2510.09665"},
                {"title": "Momento LMCache blog", "url": "https://www.gomomento.com/blog/reduce-ttft-by-50-with-lmcache-momento/"},
            ],
            "uncertain": [],
        },
    },
    {
        "file": "RAG_chunk_KV_research.json",
        "data": {
            "name": "RAG chunk KV research",
            "category": "Research",
            "official_url": "https://arxiv.org/html/2510.10129v2",
            "already_exists": "research_only",
            "existence_evidence": "TurboRAG (precomputed chunk KV, 9.4x TTFT); CacheBlend/LMCache (partial KV recompute); Cache-Craft (chunk-cache manager, 51% less redundant compute vs prefix); CacheClip, KVLink, SmartCache (NeurIPS 2025). Production adoption partial via LMCache lineage.",
            "gap_vs_vision": "Academic systems lack enterprise compliance lanes; inform Tier 3/4 engineering not buy-ready org product.",
            "summary": "Research on reusing per-chunk KV states and retrieval results instead of full prefill per query.",
            "how_it_works": "Offline precompute KV per passage; online stitch/reorder/recompute subset for cross-chunk attention; selective token recompute (CacheClip) or positional re-encoding (KVLink).",
            "integration_points": "Future RAG inference engines; LMCache codebase for CacheBlend.",
            "correctness_risks": "Naive KV concat drops quality; systems add recompute or fine-tuning to recover.",
            "cost_latency_impact": "2-9x TTFT improvements in papers; throughput 1.6-5x in Cache-Craft production-style evals.",
            "environmental_impact": "Large GPU savings if deployed at scale.",
            "cross_user_sharing": "org_wide_with_guards — chunk KV tied to public corpus chunks not user text",
            "pii_and_compliance_controls": "Only precompute KV for approved corpus chunks; never from user-uploaded ephemeral context.",
            "org_scale_patterns": "Watch LMCache/CacheBlend for productionizable Tier 3+4 merge.",
            "rollout_priority": "Monitor 6-12mo; implement simple retrieval cache now",
            "makes_sense_verdict": "yes_with_caveats",
            "makes_sense_rationale": "Validates Tier 3 priority; full chunk-KV reuse is engineering-heavy for v1.",
            "primary_sources": [
                {"title": "CacheClip", "url": "https://arxiv.org/html/2510.10129v2"},
                {"title": "TurboRAG", "url": "https://aclanthology.org/anthology-files/anthology-files/pdf/emnlp/2025.emnlp-main.334.pdf"},
                {"title": "SmartCache NeurIPS 2025", "url": "https://neurips.cc/virtual/2025/poster/116287"},
            ],
            "uncertain": [],
        },
    },
    {
        "file": "Carbon_and_sustainability.json",
        "data": {
            "name": "Carbon and sustainability",
            "category": "Impact",
            "official_url": "https://arxiv.org/html/2505.23970v2",
            "already_exists": "research_only",
            "existence_evidence": "GreenCache (Cache Your Prompt When It's Green): operational carbon down from avoided compute; embodied carbon from SSD cache storage; 12-25% net carbon reduction in evaluated scenarios with adaptive sizing.",
            "gap_vs_vision": "No mainstream gateway exposes carbon-aware cache sizing; org should track tokens avoided not only dollars.",
            "summary": "Caching reduces inference energy; large persistent KV/semantic stores add storage manufacturing emissions—net benefit depends on hit rate, cache size, grid carbon intensity.",
            "how_it_works": "GreenCache resizes cache based on load and carbon intensity (CI); high CI favors larger cache; low CI favors smaller cache to limit embodied cost.",
            "integration_points": "Platform SRE, sustainability reporting, LMCache storage tier choices.",
            "correctness_risks": "[uncertain] exact net carbon for semantic Redis vs GPU savings without org-specific measurement.",
            "cost_latency_impact": "Aligned with cost savings—fewer tokens computed.",
            "environmental_impact": "Cross-user caching multiplies avoided compute per stored entry; measure tokens_saved and estimate kg CO2e via grid factors.",
            "cross_user_sharing": "org_wide_with_guards — more users per entry improves carbon amortization",
            "pii_and_compliance_controls": "N/A to carbon; don't skip compliance for green claims.",
            "org_scale_patterns": "Report cache hit rate alongside estimated emissions avoided in ESG dashboards.",
            "rollout_priority": "Ongoing metrics after cache live",
            "makes_sense_verdict": "yes_with_caveats",
            "makes_sense_rationale": "Supports business case beyond cost; quantify after deployment.",
            "primary_sources": [
                {"title": "GreenCache paper", "url": "https://arxiv.org/html/2505.23970v2"},
            ],
            "uncertain": ["correctness_risks"],
        },
    },
    {
        "file": "Enterprise_governance_and_risks.json",
        "data": {
            "name": "Enterprise governance and risks",
            "category": "Governance",
            "official_url": None,
            "already_exists": "partial_fragment",
            "existence_evidence": "Gateways offer audit logs, RBAC, PII guardrails (Portkey, etc.). GDPR erasure and SOC2 are organizational processes—not cache-specific products. Semantic cache false positives documented in GPTCache benchmarks and vCache paper.",
            "gap_vs_vision": "Unified governance plane for all tiers and tools with prohibited cross-user answer sharing by default.",
            "summary": "Risk register for org-wide LLM caching: staleness, leakage, regulatory, model drift, insider data in coding assistants.",
            "how_it_works": "Policies: classification mandatory, retention limits, incident response for bad cache hit, periodic cache purge on corpus update, red team paraphrase tests near semantic threshold.",
            "integration_points": "Legal, security, IAM, DLP, SIEM, model risk management.",
            "correctness_risks": "Highest: Tier 2 cross-user; medium: Tier 3 wrong chunks; lower: Tier 1 stale FAQ.",
            "cost_latency_impact": "Governance overhead small vs breach or wrong contract advice cost.",
            "environmental_impact": "N/A",
            "cross_user_sharing": "org_wide_with_guards — default deny, explicit allow per route",
            "pii_and_compliance_controls": "Data minimization in cache values; encryption; access logs; DPIA before org-wide semantic; regional residency for Redis.",
            "org_scale_patterns": "Cache governance board; align with existing records retention; separate prod/stage cache namespaces.",
            "rollout_priority": "Week 0 parallel with architecture",
            "makes_sense_verdict": "strong_yes",
            "makes_sense_rationale": "Enabler for allowed cross-user reuse; not optional for regulated orgs.",
            "primary_sources": [
                {"title": "vCache correctness", "url": "https://arxiv.org/abs/2502.03771"},
                {"title": "Portkey governance features", "url": "https://portkey.ai/features/ai-gateway"},
            ],
            "uncertain": ["official_url", "environmental_impact"],
        },
    },
    {
        "file": "Build_vs_buy_and_rollout_priority.json",
        "data": {
            "name": "Build vs buy and rollout priority",
            "category": "Strategy",
            "official_url": None,
            "already_exists": "partial_fragment",
            "existence_evidence": "Buy: Portkey/LiteLLM gateway caches, Redis LangCache. Build: Tier 3 retrieval keys, lane policy, normalization. No unified 'distributed prompt cache' SKU found in 2025-2026 market scan.",
            "gap_vs_vision": "The product is integration + policy + Tier 3, not a new algorithm.",
            "summary": "Recommended sequence for enterprise RAG with thousands of users and compliance needs.",
            "how_it_works": "Phase 0: lanes + DLP. Phase 1 (wk1-2): Tier 3 retrieval cache + metrics. Phase 2 (wk3-4): Tier 4 prompt structure + provider cache_control. Phase 3 (mo2): Tier 1 exact FAQ via gateway Redis. Phase 4 (mo3+): Tier 2 semantic on faq lane only. Self-host: add LMCache if internal models.",
            "integration_points": "LiteLLM or Portkey + Qdrant + Redis + corpus version service.",
            "correctness_risks": "Skipping phases and enabling org-wide semantic first.",
            "cost_latency_impact": "Early phases capture majority of low-risk savings.",
            "environmental_impact": "Tracks cost phase—report after Phase 1.",
            "cross_user_sharing": "org_wide_with_guards — phased widen lanes as proven",
            "pii_and_compliance_controls": "Gate each phase on security sign-off for cross-user writes.",
            "org_scale_patterns": "Central platform team owns schema; product teams consume via gateway.",
            "rollout_priority": "See how_it_works phases",
            "makes_sense_verdict": "strong_yes",
            "makes_sense_rationale": "Build-vs-buy split is clear; buy gateway+Redis, build Tier3+policy.",
            "primary_sources": [
                {"title": "LiteLLM caching", "url": "https://docs.litellm.ai/docs/proxy/caching"},
                {"title": "Tool discovery synthesis (internal Phase 1)", "url": "https://github.com/zilliztech/gptcache"},
            ],
            "uncertain": ["official_url"],
        },
    },
]

def main():
    OUT.mkdir(parents=True, exist_ok=True)
    all_items = ITEMS + REMAINING
    for item in all_items:
        path = OUT / item["file"]
        data = item["data"].copy()
        if data.get("official_url") is None:
            data.pop("official_url", None)
        path.write_text(json.dumps(data, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
        print(f"Wrote {path.name}")
    print(f"Total: {len(all_items)} files")

if __name__ == "__main__":
    main()
